# Site Info
title:              "مِحسن"
description:        "میلیون ها سال انسان درست مثل حیوانات زندگی می‌کرد. بعد اتفاقی افتاد که نیروی تخیل ما را از بند رهانید. یاد گرفتیم سخن بگوییم و گوش بدهیم. تکلم با ممکن ساختن تبادل اندیشه، مردم را قادر به همکاری برای انجام ناممکن‌ها کرد. بزرگترین دستاوردهای انسان حاصل حرف زدن، و بزرگترین شکست‌هایش نتیجه حرف نزدن بوده است. در آینده بزرگترین آرزوهایمان می‌تواند به واقعیت بدل شود. با در اختیار داشتن تکنولوژی، شدنی‌ها بی حد و مرز اند. تنها باید حواسمان باشد که به حرف زدن ادامه دهیم.  ―استیون هاوکینگ "

url: https://mehsen.com
google_site_verification: Js3PpS0Bi0tAOlCK9zV-uu0W-LB4xujWT2aPvkX8p5I # Put your Google Verification here
google_analytics: 

# Author Info
author:
  name:        "محسن دستجردی زاده"
  email:       me@mehsen.com
  gravatar:    452cc758d1fe02811a25bb84c2fecb5e # Gravatar md5 hash (http://www.miraclesalad.com/webtools/md5.php)
  twitter:     dstjrd

# Social networks (contact)
social:
  -
    name: ارتباط
    url: /contact
    font_awesome: twitter-square
  -
    name: پادکست
    url: /subscribe
    font_awesome: podcast
  -
    name: حمایت
    url: /support
    font_awesome: cash
  -
    name: دوستان
    url: /favorites
    font_awesome: cash
  -
    name: English
    url: https://mehsen.com

# Podcast config
podcast:
  cover_art: /public/mehsen-podcast-1500.jpg
  statistics_prefix: http://media.blubrry.com/mehsen/
  description:  "میلیون ها سال انسان درست مثل حیوانات زندگی می‌کرد. بعد اتفاقی افتاد که نیروی تخیل ما را از بند رهانید. یاد گرفتیم سخن بگوییم و گوش بدهیم. تکلم با ممکن ساختن تبادل اندیشه، مردم را قادر به همکاری برای انجام ناممکن‌ها کرد. بزرگترین دستاوردهای انسان حاصل حرف زدن، و بزرگترین شکست‌هایش نتیجه حرف نزدن بوده است. در آینده بزرگترین آرزوهایمان می‌تواند به واقعیت بدل شود. با در اختیار داشتن تکنولوژی، شدنی‌ها بی حد و مرز اند. تنها باید مطمئن شویم که به حرف زدن ادامه خواهیم داد.  ―استیون هاوکینگ "
  summary: "با در اختیار داشتن تکنولوژی، شدنی‌ها بی حد و مرز اند. تنها باید مطمئن شویم که به حرف زدن ادامه خواهیم داد...  ―استیون هاوکینگ "
  castbox: "https://castbox.fm/channel/id1446853"

# Site texts
texts:
  about_author:     "درباره محسن" # About The Author
  back_home:        "بازگشت به خانه" # Back to Home
  back:             "بازگشت" # Back
  see_more:         "دیدن باقی..." # See More Posts
  posts:            "ده پست آخر:" # Last <home_post_count> posts

# Site Settings
baseurl:            "" # Base URL must end WITHOUT a slash, default: ""
permalink:          /posts/:title # Post permalink
enforce_ssl:        "" # Leave empty if your domain doesn't have https, write the domain if it has
timezone:           Asia/Tehran # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
date_format:        "%b %d, %Y"
direction:          rtl # Text direction. ltr/rtl
lang:               fa # http://www.w3schools.com/tags/ref_language_codes.asp
header_image:       /public/top.jpg # "gravatar" or url to an image
home_post_count:    10
disqus:             'mehsen'
keywords: "Podcast, Shabane, Persian, Iran, Irani, ایران, ایرانی, پادکست, شبانه, فارسی, پادکست فارسی"

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed
excerpt_separator: "<!--more-->"

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

compress_html:
    clippings:      all
    ingore:
        envs:       [ "test" ]

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
